### ISSUE TITLE
Extracting this into a library

### ISSUE THREAD

**Issue by anzecesar** [sangria-graphql/sangria-akka-http-example#23]
Hi,

has anyone ever considered extracting the boilerplate code into a library?

it would be neat to do
```
libraryDependencies += "org.sangria-graphql"    %% "sangria-akka-http"               % sangriaVersion

route = 
  graphQLPlayground ~
  prepareGraphQLRequest(...)
```

It would cut down on the boilerplate and make the adoption of graphql in Scala even simpler. 

Of course, implementations for other http server libraries could be made as needed.

**Comment by nickhudkins** [comment]
Hi @andyczerwonka that's what the most recent PR is intended to start. The one thing I will mention is that currently I wrote `SangriaAkkaHttp.scala` assuming the use of `circe`. I've given it some thought, but wanted to at LEAST have folks not needing to pay much attention to that object.

Next step would be to make sure it can handle any of our supported JSON libraries, and then I would be happy to create `sangria-akka-http`.

We also would happily accept a PR doing this :)

**Comment by andyczerwonka** [comment]
Hi @nickhudkins, I think you meant to ping @anzecesar

**Comment by anzecesar** [comment]
Hi,

that's a good point. Looking at the code, the json usage is more or less internal, but it would still be nice to use whichever provided json library you want.

A mini spec:
1. we use use akka's [un/marshalling](https://doc.akka.io/docs/akka-http/current/common/unmarshalling.html) framework
2. we [don't use Json directly](https://github.com/sangria-graphql/sangria-akka-http-example/blob/master/src/main/scala/SangriaAkkaHttp.scala#L38-L50), instead marshall to/from case classes
3. all methods dealing with json get an `(implicit un/marshaller: FromXXXUn/Marshaller)`
4. json impl specific library provides un/marshallers, which the user just needs to import at usage site

Wdyt? Am I missing something?
It's been a while since I properly used akka-http or Sangria :).

I can try to do this. I'm just working on adding Sangria to a project so it's kind of in scope for me atm :).

**Comment by anzecesar** [comment]
Here is a first, rough around the edges, implementation: https://github.com/sangria-graphql/sangria-akka-http-example/pull/24

I also noticed there aren't any tests, which I should really add :).
